insert into comicbooks_info_new(
actualizado_externamente,
api_detail_url,
fecha_tapa,
id_comicbook_info,
id_volume,
nombre_volumen,
nota,
numero,
orden,
rating,
resumen,
titulo,
url)
select actualizado_externamente,
api_detail_url,
fecha_tapa,
id_comicbook_info,
id_volume,
nombre_volumen,
nota,
numero,
orden,
rating,
resumen,
titulo,
''
from comicbooks_info

CREATE TABLE "comicbooks_info_new" (
	"id_comicbook_info" INTEGER NOT NULL,
	titulo VARCHAR NOT NULL,
	id_volume VARCHAR NOT NULL,
	nombre_volumen VARCHAR NOT NULL,
	numero VARCHAR NOT NULL,
	fecha_tapa INTEGER NOT NULL,
	resumen VARCHAR NOT NULL,
	nota VARCHAR NOT NULL,
	rating FLOAT NOT NULL,
	api_detail_url VARCHAR NOT NULL,
	url VARCHAR NOT NULL,
	orden FLOAT NOT NULL,
	actualizado_externamente BOOLEAN NOT NULL,
	PRIMARY KEY ("id_comicbook_Info"),
	CHECK (actualizado_externamente IN (0, 1))
);
